# Copyright 2026 RiskDataScience GmbH
# SPDX-License-Identifier: Apache-2.0
"""Versionierter Excel-Vertrag; enthält ausschließlich Strukturmetadaten."""

CONTRACT_VERSION = "1.1.0"
COMMON = [
    "record_id",
    "business_key",
    "version_no",
    "as_of_date",
    "valid_from",
    "valid_to",
    "known_from",
    "known_to",
    "is_official",
    "record_status",
    "source_system",
    "source_record_id",
]

WORKBOOKS = {
    "FIA_IN_00_Run_Control.xlsx": (
        "run_control",
        [
            "run_key",
            "profile_id",
            "policy_id",
            "rule_set_id",
            "contract_version",
            "reporting_date",
            "knowledge_time",
            "view",
        ],
    ),
    "FIA_IN_01_Entities_Scopes.xlsx": (
        "entities",
        ["entity_id", "entity_name", "functional_currency", "consolidation_scope"],
    ),
    "FIA_IN_02_Parties_Credit_Status.xlsx": (
        "parties",
        ["party_id", "rating_orig", "rating_current", "default_flag", "watchlist", "forbearance"],
    ),
    "FIA_IN_03_Instruments_Contracts.xlsx": (
        "instruments",
        [
            "entity_id",
            "instrument_id",
            "instrument_type",
            "portfolio",
            "currency",
            "transaction_price",
            "gross_amount",
            "fair_value",
            "transaction_costs",
            "business_model",
            "liability",
            "equity",
            "held_for_trading",
            "fair_value_option",
            "fvoci_equity_election",
            "designation_approval_id",
            "hybrid_contract",
            "host_contract_type",
            "embedded_derivative_separated",
            "contingent_feature",
            "simplified",
            "poci",
            "impairment_scope",
            "ecl_method",
            "provision_rate",
            "poci_initial_lifetime_ecl",
            "eir",
            "credit_adjusted_eir",
            "rate_type",
            "reset_rate",
            "undrawn",
            "guarantee_amount",
            "overlay",
            "overlay_id",
            "overlay_owner",
            "overlay_approved",
            "overlay_expiry",
            "overlay_thesis",
            "overlay_double_count_checked",
            "initial_recognition_date",
            "maturity_date",
            "regular_way",
            "trade_date_policy",
            "electronic_payment_election",
            "payment_irrevocable",
            "withdrawal_access_practical",
            "settlement_risk_insignificant",
            "settlement_short_period",
            "scope_assessment",
            "recognition_status",
            "own_use",
            "nature_dependent_contract",
            "purchaser_net_buyer",
            "quantity_consistent_expected_usage",
            "sale_timing_uncontrollable",
            "repurchase_within_reasonable_time",
            "interface_standard",
            "interface_decision_id",
            "interface_approved",
            "regulatory_approach",
            "regulatory_default_flag",
            "regulatory_expected_loss",
        ],
    ),
    "FIA_IN_04_Cashflows_Fees_EIR.xlsx": (
        "cashflows",
        [
            "cashflow_id",
            "instrument_id",
            "scenario_id",
            "year_fraction",
            "amount",
            "cashflow_type",
            "contractual",
            "expected",
            "include_in_eir",
        ],
    ),
    "FIA_IN_05_Accounting_Balances.xlsx": (
        "opening_balances",
        [
            "instrument_id",
            "opening_gross",
            "opening_allowance",
            "opening_fvoci_reserve",
            "opening_hedge_reserve",
            "ledger_gross",
            "ledger_allowance",
        ],
    ),
    "FIA_IN_06_Classification_SPPI.xlsx": (
        "classification_inputs",
        [
            "instrument_id",
            "business_model",
            "principal_consistent",
            "basic_interest",
            "leverage",
            "modified_time_value_pass",
            "prepayment_compensation_reasonable",
            "extension_basic",
            "non_recourse_pass",
            "cli_lookthrough_pass",
            "contingent_feature_basic",
            "de_minimis_or_non_genuine",
            "sppi_override",
            "designation",
            "approval_id",
            "business_model_change",
        ],
    ),
    "FIA_IN_07_Collateral_Recoveries.xlsx": (
        "collateral",
        [
            "collateral_id",
            "instrument_id",
            "collateral_type",
            "fair_value",
            "haircut",
            "cost",
            "recovery_year",
            "allocated_amount",
            "separately_recognised",
        ],
    ),
    "FIA_IN_08_Staging_SICR.xlsx": (
        "staging_inputs",
        [
            "instrument_id",
            "impairment_scope",
            "prior_stage",
            "days_past_due",
            "rating_orig",
            "rating_current",
            "lifetime_pd_orig",
            "lifetime_pd_current",
            "watchlist",
            "forbearance",
            "unlikely_to_pay",
            "forward_looking_sicr",
            "credit_impaired",
            "simplified",
            "poci",
            "low_credit_risk",
            "collective_assessment",
            "sicr_rebuttal",
            "sicr_override",
            "override_reason",
            "override_approved",
            "override_expiry",
            "months_since_cure",
            "months_since_forbearance",
        ],
    ),
    "FIA_IN_09_PD_Models_Curves.xlsx": (
        "pd_curves",
        [
            "instrument_id",
            "scenario_id",
            "year",
            "marginal_pd",
            "model_version_id",
            "model_owner",
            "validation_status",
            "approval_id",
        ],
    ),
    "FIA_IN_10_LGD_Models.xlsx": (
        "lgd_profiles",
        [
            "instrument_id",
            "scenario_id",
            "year",
            "resolution_path",
            "lgd",
            "recovery_present_value",
            "workout_cost",
            "model_version_id",
            "model_owner",
            "validation_status",
            "approval_id",
        ],
    ),
    "FIA_IN_11_EAD_CCF_Profiles.xlsx": (
        "ead_profiles",
        [
            "instrument_id",
            "scenario_id",
            "year",
            "ead",
            "ccf",
            "prepayment_rate",
            "behavioural_horizon_years",
            "model_version_id",
            "model_owner",
            "validation_status",
            "approval_id",
        ],
    ),
    "FIA_IN_12_Macro_Scenarios.xlsx": (
        "scenarios",
        [
            "scenario_id",
            "probability",
            "scenario_version",
            "forecast_horizon_years",
            "mean_reversion_method",
            "approved_by",
            "approved_at",
        ],
    ),
    "FIA_IN_13_Modifications_Writeoffs.xlsx": (
        "events",
        [
            "event_id",
            "instrument_id",
            "event_type",
            "amount",
            "event_date",
            "approved",
            "qualitative_substantial",
            "ten_percent_ratio",
            "modified_present_value",
            "derecognition_approved",
            "risks_rewards_transferred",
            "risks_rewards_retained",
            "control_retained",
            "pass_through_arrangement",
            "partial_transfer",
            "continuing_involvement_amount",
            "reason_code",
        ],
    ),
    "FIA_IN_14_Fair_Value_Market_Data.xlsx": (
        "market_data",
        [
            "market_data_id",
            "instrument_id",
            "fair_value",
            "fx_rate",
            "ifrs13_level",
            "valuation_model",
            "valuation_status",
            "total_fv_change",
            "own_credit_change",
            "own_credit_oci_mismatch",
            "day_one_difference",
        ],
    ),
    "FIA_IN_15_Hedge_Accounting.xlsx": (
        "hedges",
        [
            "relationship_id",
            "hedge_type",
            "hedging_instrument_eligible",
            "hedged_item_eligible",
            "risk_component_eligible",
            "designation_documented",
            "risk_management_objective",
            "hedging_change",
            "hedged_change",
            "designated",
            "economic_relationship",
            "credit_risk_dominates",
            "hedge_ratio",
            "target_hedge_ratio",
            "rebalancing_required",
            "discontinue",
            "forecast_transaction_expected",
            "nature_dependent_electricity_hedge",
            "variable_nominal_volume",
            "volume_assumptions_documented",
            "option_time_value_change",
            "forward_element_change",
            "basis_spread_change",
            "recycle_amount",
            "basis_adjustment",
        ],
    ),
    "FIA_IN_16_Rules_Parameters.xlsx": (
        "parameters",
        ["parameter_id", "parameter_value", "unit", "policy_id", "rule_set_id", "source_reference"],
    ),
    "FIA_IN_17_Bank_Mappings.xlsx": (
        "mappings",
        [
            "mapping_id",
            "mapping_type",
            "external_value",
            "canonical_value",
            "valid_from",
            "valid_to",
        ],
    ),
    "FIA_IN_18_Backtesting_Observations.xlsx": (
        "backtesting",
        [
            "observation_id",
            "model_type",
            "model_version_id",
            "challenger_flag",
            "segment",
            "observation_date",
            "predicted_value",
            "actual_value",
            "exposure_weight",
            "outcome_flag",
            "release_amount",
            "model_owner",
            "validation_status",
            "approval_id",
        ],
    ),
}

DOMAINS = {
    "business_model": "HOLD_TO_COLLECT|HOLD_TO_COLLECT_AND_SELL|OTHER",
    "view": "REFERENCE|MANAGEMENT|IMPACT|OFFICIAL",
    "record_status": "ACTIVE|INACTIVE",
    "model_type": "PD|LGD|EAD|CCF|STAGING|SCENARIO|OVERLAY",
    "validation_status": "VALIDATED|CONDITIONALLY_VALIDATED|EXPIRED|REJECTED",
}
